apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: {{ .Release.Name }}
spec:
  ports:
  - name: db-port
    port: 3306
    nodePort: {{ .Values.networks.nodeport.mariadb }}
    protocol: TCP
    targetPort: db-port
  selector:
    app: mariadb
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: biris.manse
        #command:
        #- sh
        #- -c
        #- /usr/local/bin/docker-entrypoint.sh
        #- while :; do echo 'Hello'; sleep 100 ; done 
        image: "{{ .Values.image.repository }}/mariadb:{{ .Values.image.mariadb }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mariadb
        ports:
        - name: db-port
          containerPort: 3306
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
