apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: {{ .Release.Name }}
spec:
  ports:
  - name: db-port
    port: 5432
    nodePort: {{ .Values.networks.nodeport.postgresql }}
    protocol: TCP
    targetPort: db-port
  selector:
    app: postgres
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: test
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: biris.manse
        image: "{{ .Values.image.repository }}/postgres:{{ .Values.image.postgresql }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: postgres
        ports:
        - name: db-port
          containerPort: 5432
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
